# Generated by Django 4.2.7 on 2024-10-22 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tax_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 13, 27, 9, 583906, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
